name: Deploy on push
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
      - run: npm i
      - run: npm run deploy
