name: Deploy on push
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
      - name: Install dependencies
        run: npm i
      - name: Deploy webiste
        env:
          GH_TOKEN: ${{ github.token }}
          GIT_USER: $(gh api /users/${GITHUB_ACTOR} | jq .name -r)
        run: GIT_USER="$(gh api /users/${GITHUB_ACTOR} | jq .name -r)" npm run deploy
