name: Deploy on push
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@v4
          with:
            node-version: '21.5.0'
      - name: Install dependencies
        run: npm i
      - name: Deploy
        run: npm run deploy
