name: Deploy on push
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: docs
          git-user: $SOME_USERNAME
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages