name: Deploy on push
on: [push]

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
      - name: Install dependencies
        run: npm i
      - name: Deploy webiste
        env:
          GH_TOKEN: ${{ github.token }}
          GIT_USER: GitHub Actions
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: npm run deploy
